#include <iostream>
#include <vector>
#include <algorithm>
#include <list>
#include <queue>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <deque>

using std::vector;
using std::list;
using std::queue;
using std::set;
using std::map;
using std::unordered_map;
using std::unordered_set;
using std::deque;
using std::cin;
using std::cout;
using std::cerr;
using std::endl;
